version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run: echo "Build server"
      - run: npm install
      - run: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
workflows:
  version: 2.1
  install_and_build:
    jobs:
      - build
